name: ci

jobs:
  diffend:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Install latest bundler
        run: gem install bundler --no-document
      - name: Install Diffend plugin
        run: bundle plugin install diffend
      - name: Bundle Secure
        run: bundle secure

  coditsu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run Coditsu
        env:
          CODITSU_API_KEY: ${{ secrets.CODITSU_API_KEY }}
          CODITSU_API_SECRET: ${{ secrets.CODITSU_API_SECRET }}
        run: \curl -sSL https://api.coditsu.io/run/ci | bash

on:
  push:
  schedule:
    - cron:  '0 1 * * *'
