name: ci

jobs:
  coditsu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run Coditsu
        env:
          CODITSU_API_KEY: ${{ secrets.CODITSU_API_KEY }}
          CODITSU_API_SECRET: ${{ secrets.CODITSU_API_SECRET }}
        run: \curl -sSL https://api.coditsu.io/run/ci | bash

on:
  push:
  schedule:
    - cron:  '0 1 * * *'
